# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Navi-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navi-App
  pod 'AlamofireImage'
  pod 'Parse'
  pod "MessageInputBar"

  target 'Navi-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Navi-AppUITests' do
    # Pods for testing
  end

end
